"""
Markdown ISR renderer using Jinja2 templates.
"""

from datetime import datetime
from jinja2 import Environment, BaseLoader

ISR_TEMPLATE = """# Incident Summary Report

**Incident:** {{ incident.title }}
**Severity:** {{ incident.severity }}
**Status:** {{ incident.status }}
**Start:** {{ incident.startTs }}
**Resolved:** {{ incident.resolvedTs or 'N/A' }}
**MTTR:** {{ mttr_minutes }} minutes
**Affected Systems:** {{ incident.affectedSystems | join(', ') }}
**Report Generated:** {{ generated_at }}

---

## Executive Summary

{{ executive_summary }}

---

## Participants

| Name | Role | Speaking Time |
|------|------|---------------|
{% for p in participants -%}
| {{ p.speakerLabel or 'Unknown' }} | {{ p.role }} | {{ (p.speakingTimeSeconds // 60) }}m {{ (p.speakingTimeSeconds % 60) }}s |
{% endfor %}

---

## Incident Timeline

{% for entry in timeline | sort(attribute='ts') -%}
- **{{ entry.ts | format_time }}** `[{{ entry.type }}]` {{ entry.title }}
{% endfor %}

---

## Confirmed Facts

{% for fact in facts -%}
{{ loop.index }}. {{ fact.content }}
   - *Confidence: {{ (fact.confidence * 100) | round | int }}% · {{ fact.createdAt | format_time }}*
{% endfor %}

---

## Hypotheses

{% for h in hypotheses -%}
{{ loop.index }}. **{{ h.status }}** — {{ h.content }}
   - *Confidence: {{ (h.confidence * 100) | round | int }}%*
{% endfor %}

---

## Key Decisions

{% for d in decisions -%}
{{ loop.index }}. {{ d.content }}
   - *{{ d.createdAt | format_time }}*
{% endfor %}

---

## Action Items

| # | Description | Owner | Status |
|---|-------------|-------|--------|
{% for a in action_items -%}
| {{ loop.index }} | {{ a.content }} | {{ a.ownerName or '⚠️ Unassigned' }} | {{ a.status }} |
{% endfor %}

---

## Open Questions

{% for q in questions -%}
{{ loop.index }}. {{ q.content }} *({{ q.status }})*
{% endfor %}

---

## Conflicts Detected

{% for c in conflicts -%}
{{ loop.index }}. **{{ c.status }}** — {{ c.description }}
{% endfor %}

---

## What Went Well

*(To be completed in team retrospective)*

## What Needs Improvement

*(To be completed in team retrospective)*

## Action Items for Prevention

*(To be completed in team retrospective)*

---

*Generated by VAIC — Voice AI Incident Commander*
"""


def _format_time(ts_str: str) -> str:
    try:
        dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        return dt.strftime("%H:%M:%S UTC")
    except Exception:
        return ts_str


def render_markdown_isr(context: dict) -> str:
    env = Environment(loader=BaseLoader())
    env.filters["format_time"] = _format_time
    template = env.from_string(ISR_TEMPLATE)
    return template.render(**context)
